//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFashion.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.OrderProes = new HashSet<OrderPro>();
        }

        public int IDCus { get; set; }

        [Required (ErrorMessage = "Vui lòng nhập Họ tên!")]
        public string NameCus { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập Username!")]
        public string AccountCus { get; set; }

        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$")] //ít nhất 1 chữ hoa, 1 chữ thường, 1 số
        [Required(ErrorMessage = "Vui lòng nhập mật khẩu!")]
        public string PassCus { get; set; }
        //Ít nhất 8 nhiều nhất 15
      
        public Nullable<bool> Gender { get; set; }
        
        public string PhoneCus { get; set; }

        [RegularExpression(@"^[a-z0-9](\.?[a-z0-9]){4,}@gmail\.com$")]
        [Required(ErrorMessage = "Vui lòng nhập Email!")]
        public string EmailCus { get; set; }

        public string Address { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPro> OrderProes { get; set; }
    }
}
